BOOK_MAP = {
    "Al-Amali-Mufid": "الأمالي (للمفید)",
    "Al-Amali-Saduq": "الأمالی (للصدوق)",
    "Al-Kafi-Volume-1-Kulayni": "الکافي",
    "Al-Kafi-Volume-2-Kulayni": "الکافي",
    "Al-Kafi-Volume-3-Kulayni": "الکافي",
    "Al-Kafi-Volume-4-Kulayni": "الکافي",
    "Al-Kafi-Volume-5-Kulayni": "الکافي",
    "Al-Kafi-Volume-6-Kulayni": "الکافي",
    "Al-Kafi-Volume-7-Kulayni": "الکافي",
    "Al-Kafi-Volume-8-Kulayni": "الکافي",
    "Al-Khisal-Saduq": "الخصال",
    "Al-Tawhid-Saduq": "التوحيد",
    "Fadail-al-Shia-Saduq": "فضائل الشیعة",
    "Kamil-al-Ziyarat-Qummi": "کامل الزيارات",
    "Kitab-al-Ghayba-Numani": "الغيبة (للنعمانی)",
    "Kitab-al-Ghayba-Tusi": "الغيبة (للطوسی)",
    "Kitab-al-Mumin-Ahwazi": "المؤمن",
    "Kitab-al-Zuhd-Ahwazi": "الزهد",
    "Maani-al-Akhbar-Saduq": "معاني الأخبار",
    "Nahj-al-Balagha-Radi": "نهج البلاغة",
    "Sifat-al-Shia-Saduq": "صفات الشیعة",
    "Thawab-al-Amal-wa-iqab-al-Amal-Saduq": "ثواب الأعمال و عقاب الأعمال",
    "Uyun-akhbar-al-Rida-Volume-1-Saduq": "عيون أخبار الرضا عليه السلام",
    "Uyun-akhbar-al-Rida-Volume-2-Saduq": "عيون أخبار الرضا عليه السلام",
}
